spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://127.0.0.1:3306/lexindia_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8080}

app:
  auth:
    session-ttl-hours: ${SESSION_TTL_HOURS:24}
