create table profiles (
    id uuid primary key,
    full_name varchar(255),
    email varchar(255) not null unique,
    role varchar(50) not null,
    avatar_url varchar(500),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table app_users (
    id uuid primary key references profiles(id) on delete cascade,
    password_hash varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table auth_sessions (
    token varchar(100) primary key,
    user_id uuid not null references profiles(id) on delete cascade,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null
);

create table articles (
    id uuid primary key,
    category varchar(100) not null,
    number integer not null,
    title varchar(255) not null,
    full_text text,
    explanation text,
    key_points text,
    important_cases text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table legal_insights (
    id uuid primary key,
    expert_id uuid references profiles(id) on delete set null,
    title varchar(255) not null,
    content text not null,
    category varchar(100),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table case_references (
    id uuid primary key,
    title varchar(255) not null,
    citation varchar(255),
    summary text,
    article_id uuid references articles(id) on delete set null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table advisory_requests (
    id uuid primary key,
    citizen_id uuid references profiles(id) on delete cascade,
    expert_id uuid references profiles(id) on delete set null,
    question text not null,
    category varchar(100),
    status varchar(50) not null,
    urgent boolean not null,
    response text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table quizzes (
    id bigint primary key,
    title varchar(255) not null,
    description text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table quiz_questions (
    id bigint generated by default as identity primary key,
    quiz_id bigint not null references quizzes(id) on delete cascade,
    question text not null,
    options text not null,
    correct_answer integer not null,
    explanation text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table forum_topics (
    id uuid primary key,
    title varchar(255) not null,
    content text not null,
    author_id uuid references profiles(id) on delete cascade,
    category varchar(100),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table forum_replies (
    id uuid primary key,
    topic_id uuid references forum_topics(id) on delete cascade,
    author_id uuid references profiles(id) on delete cascade,
    content text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);
